module.exports = [
  'OTH',     'PCS',     'NOS',    'KGS',   'UNT',    'BOX',
  'LTR',     'PAC',     'EACH',   'MTR',   'SET',    'SQF',
  'POCH',    'BTL',     'BAG',    'CASE',  'LAD',    'JAR',
  'PET',     'FT',      'GMS',    'TBS',   'STRP',   'ROL',
  'COIL',    'DOZ',     'QTL',    'PRS',   'NONE',   'BOR',
  'PAIR',    'DAY',     'MTS',    'SQM',   'CTN',    'LOT',
  'PLT',     'TON',     'PERSON', 'MTH',   'SHEETS', 'CAN',
  'BDL',     'COPY',    'MLT',    'IN',    'TIN',    'KIT',
  'PAD',     'CPS',     'HRS',    'KME',   'MLG',    'TUB',
  'BARREL',  'RFT',     'CBM',    'HEGAR', 'DRM',    'GLS',
  'PRT',     'RMT',     'VIAL',   'BCK',   'YRS',    'CFT',
  'MAN-DAY', 'REEL',    'BUN',    'PATTA', 'AMP',    'TKT',
  'CTS',     'BLISTER', 'CCM',    'HOLES', 'REAM',   'BRASS',
  'PADS',    'RIM',     'KW',     'W',     'NIGHT',  'LINES',
  'LGTH',    'TRIP',    'LPSM',   'WDTH',  'SQCM',   'SHFT',
  'AU',      'MINS',    'BAL',    'GRS',   'THD',    'SAC',
  'MM',      'KLR',     'CUFT',   'SEC',
'CMS',   'YDS', 'SQIN',
'UGS',   'BOU', 'WEEK',
'ANA',   'TGM', 'GGR',
'CHUDI', 'SQY', 'BKL',
'CNT',   'CFM', 'GYD'
  ]
  
